### ISSUE TITLE
Make it not show media if "Show linked images inline with chat" is unchecked.

### ISSUE THREAD

**Issue by iiiGerardoiii** [xlexi/Textual-Inline-Media#10]
I'm at work and afraid of someone posting a porn link or any NSFW link on chat. Even though I disabled "Show linked images inline with chat" in the Textual preferences, the ones that Textual-Inline-Media picks are still shown.

**Comment by SuperManifolds** [comment]
This is something that was intended from the start but for some reason was just completely forgotten by me, will be in the next update.
