### ISSUE TITLE
Close button?

### ISSUE THREAD

**Issue by huphtur** [xlexi/Textual-Inline-Media#43]
Possible to add a close button? Similar to Textual's built in image viewer:

<img width="459" alt="q5p4ob0" src="https://cloud.githubusercontent.com/assets/469438/11594222/14bc5b4e-9aa9-11e5-87ec-dd376d7b6a55.png">

**Comment by SuperManifolds** [comment]
I have decided against this because it will look out of place and over sized in many of the previews, for example the website preview one. However you can hide a preview by holding shift whilst clicking on it
