### ISSUE TITLE
Help with compilation error

### ISSUE THREAD

**Issue by random4t4x14** [xlexi/Textual-Inline-Media#44]
I was hoping you could provide build instructions?  When I attempt to compile I get some errors, specifically - 

Ld /Users/brandon/Library/Developer/Xcode/DerivedData/Textual_Inline_Media-abicuupjdnixsvdqrudqhmoikjmw/Build/Products/Debug/Textual\ Inline\ Media.bundle/Contents/MacOS/Textual\ Inline\ Media normal x86_64
    cd /Users/brandon/GitHub/Textual-Inline-Media
    export MACOSX_DEPLOYMENT_TARGET=10.11
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/brandon/Library/Developer/Xcode/DerivedData/Textual_Inline_Media-abicuupjdnixsvdqrudqhmoikjmw/Build/Products/Debug -F/Users/brandon/Library/Developer/Xcode/DerivedData/Textual_Inline_Media-abicuupjdnixsvdqrudqhmoikjmw/Build/Products/Debug -F/Applications/Textual.app/Contents/Frameworks -F/Users/brandon/GitHub/Textual-Inline-Media -F/Users/brandon/GitHub/Textual-Inline-Media/Textual -FInline -FMedia/Frameworks -filelist /Users/brandon/Library/Developer/Xcode/DerivedData/Textual_Inline_Media-abicuupjdnixsvdqrudqhmoikjmw/Build/Intermediates/Textual\ Inline\ Media.build/Debug/Textual\ Inline\ Media.build/Objects-normal/x86_64/Textual\ Inline\ Media.LinkFileList -Xlinker -rpath -Xlinker @executable_path/../Frameworks -Xlinker -rpath -Xlinker @loader_path/../Frameworks -mmacosx-version-min=10.11 -bundle_loader /Applications/Textual.app/Contents/MacOS/Textual -fobjc-arc -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/macosx -Xlinker -add_ast_path -Xlinker /Users/brandon/Library/Developer/Xcode/DerivedData/Textual_Inline_Media-abicuupjdnixsvdqrudqhmoikjmw/Build/Intermediates/Textual\ Inline\ Media.build/Debug/Textual\ Inline\ Media.build/Objects-normal/x86_64/Textual_Inline_Media.swiftmodule -framework Sparkle -framework AutoHyperlinks -framework CocoaExtensions -Xlinker -dependency_info -Xlinker /Users/brandon/Library/Developer/Xcode/DerivedData/Textual_Inline_Media-abicuupjdnixsvdqrudqhmoikjmw/Build/Intermediates/Textual\ Inline\ Media.build/Debug/Textual\ Inline\ Media.build/Objects-normal/x86_64/Textual\ Inline\ Media_dependency_info.dat -o /Users/brandon/Library/Developer/Xcode/DerivedData/Textual_Inline_Media-abicuupjdnixsvdqrudqhmoikjmw/Build/Products/Debug/Textual\ Inline\ Media.bundle/Contents/MacOS/Textual\ Inline\ Media

ld: warning: directory not found for option '-F/Users/brandon/GitHub/Textual-Inline-Media/Textual'
ld: warning: directory not found for option '-FInline'
ld: warning: directory not found for option '-FMedia/Frameworks'

Thanks!

**Comment by SuperManifolds** [comment]
what version of OSX are you using?

**Comment by random4t4x14** [comment]
Hey, I'm using Mac OS X 10.11, and I was using Xcode 7.2 to compile it.

**Comment by SuperManifolds** [comment]
Is this the entire error log? If not please post the entire thing, preferably using gist.github.com
